import type { RouteComponent } from "vue-router";

export const views: Record<
  RouterPage.LastDegreeRouteKey,
  RouteComponent | (() => Promise<RouteComponent>)
> = {
  403: () => import("./_pubilc/403/index.vue"),
  404: () => import("./_pubilc/404/index.vue"),
  500: () => import("./_pubilc/500/index.vue"),
   login: () => import("./_pubilc/login/index.vue"),
  website_home: () => import("./website/homepage/index.vue"),
  lease: () => import("./website/leasepage/index.vue"),
  lease_home: () => import("./website/leasepage/HouseMain.vue"),
  lease_map: () => import("./website/leasepage/HouseMap.vue"),
  service: () => import("./website/servicepage/index.vue"),
  publish: () => import("./website/publishpage/index.vue"),
  house_detail: () => import("./website/housepage/index.vue"),
  about: () => import("./website/aboutpage/index.vue"),
  management_user: () => import("./admin/management/user/index.vue"),
  management_house: () => import("./admin/management/house/index.vue"),
  management_lease: () => import("./admin/management/lease/index.vue"),
  management_city: () => import("./admin/management/city/index.vue"),

  admin_home:() => import("./admin/home.vue"),
  houseComment_list:() => import("./admin/houseCommentList.vue"),
  houseInfo_list:() => import("./admin/houseInfolist.vue"),
  houselease_list:() => import("./admin/houseleaseList.vue"),
  admin_city_list:() => import("./admin/citylist.vue"),
  admin_user:() => import("./admin/management/user/index.vue"),
  notice_list:() => import("./admin/noticeList.vue"),
  admin_about:() => import("./admin/about.vue"),
  "not-found": () => import("./_pubilc/not-found/index.vue"),
  // component_table: undefined,
  // 'constant-page': undefined,
  // dashboard_analysis: undefined,
  // dashboard_workbench: undefined,
  // document_naive: undefined,
  // document_project: undefined,
  // 'document_project-link': undefined,
  // document_vite: undefined,
  // document_vue: undefined,
  // exception_403: undefined,
  // exception_404: undefined,
  // exception_500: undefined,
  // function_tab: undefined,
  // 'function_tab-detail': undefined,
  // 'function_tab-multi-detail': undefined,
  // login: undefined,
  // management_auth: undefined,
  // management_role: undefined,
  // management_route: undefined,
  // management_user: undefined,
  // 'multi-menu_first_second': undefined,
  // 'multi-menu_first_second-new_third': undefined,
  // 'not-found': undefined,
  // plugin_charts_antv: undefined,
  // plugin_charts_echarts: undefined,
  // plugin_copy: undefined,
  // plugin_editor_markdown: undefined,
  // plugin_editor_quill: undefined,
  // plugin_icon: undefined,
  // plugin_map: undefined,
  // plugin_print: undefined,
  // plugin_swiper: undefined,
  // plugin_video: undefined
};
